# Generated by Django 4.2.2 on 2023-06-22 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_alter_producto_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='oferta',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
