# Generated by Django 4.2.2 on 2023-07-10 16:43

from django.db import migrations, models
import django.db.models.deletion
import producto.models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
        migrations.AddField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(blank=True, default=producto.models.default_product_image, help_text='Imagen de la categoria', null=True, upload_to=producto.models.nombreImagen),
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, default=producto.models.default_product_image, help_text='Imagen del producto', null=True, upload_to=producto.models.nombreImagen)),
                ('color', models.CharField(max_length=26)),
                ('stock', models.IntegerField(blank=True, help_text='Cantidad del producto del color agg', null=True)),
                ('producto_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='producto.producto')),
            ],
        ),
    ]
