# Generated by Django 4.2.2 on 2023-06-21 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='porcentaje_iva',
            field=models.DecimalField(decimal_places=1, help_text='Porcentaje del iva ej = 16 - 19 ...', max_digits=3),
        ),
    ]
