# Generated by Django 4.2.2 on 2023-07-07 23:33

from django.db import migrations, models
import producto.models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0007_rename_imagen_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(blank=True, default=producto.models.default_product_image, help_text='Imagen de la categoria', null=True, upload_to=producto.models.nombreImagen),
        ),
    ]
