# Generated by Django 4.2.2 on 2023-06-22 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producto', '0004_producto_oferta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del cliente', max_length=50)),
                ('correo_electronico', models.EmailField(help_text='Correo del cliente', max_length=40, unique=True)),
                ('telefono', models.CharField(help_text='Telefono del cliente', max_length=15)),
                ('ciudad', models.CharField(help_text='Ciudad del cliente', max_length=30)),
                ('direccion', models.CharField(help_text='Direccion del cliente Formato Cll or Cr + ##-##', max_length=50)),
                ('tipo_persona', models.CharField(choices=[('Juridica', 'Juridica'), ('Natural', 'Natural')], help_text='Tipo juridica de Cliente', max_length=50)),
                ('nit', models.CharField(help_text='Nit de Cliente', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Producto_Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.cliente')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='producto.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(help_text="Estado del pedido 'Activo o inactivo'", max_length=20)),
                ('cantidad', models.IntegerField(help_text='Cantidad del pedido', max_length=10)),
                ('total', models.DecimalField(blank=True, decimal_places=2, help_text='Total del pedido', max_digits=20, null=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True, help_text='Fecha creacion')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('numero_factura', models.IntegerField(help_text='Number of Factura', primary_key=True, serialize=False)),
                ('metodo_pago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Credito', 'Credito'), ('Debito', 'Debito')], help_text='Metodo de pago', max_length=20)),
                ('cantidad', models.IntegerField(max_length=20)),
                ('total', models.DecimalField(decimal_places=2, help_text='Total', max_digits=20)),
                ('fecha_Factura', models.DateField(auto_now_add=True)),
                ('feca_Vencimiento', models.DateField(blank=True, help_text='Fecha de vencimiento del credito de la factura', null=True)),
                ('descripcion', models.TextField(help_text='Descripcion de la factura')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.cliente')),
            ],
        ),
    ]
