# Generated by Django 4.2.2 on 2023-06-22 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='producto_cliente',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='producto_cliente',
            name='producto',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nit',
            field=models.CharField(help_text='Nit de Cliente', max_length=15, null=True),
        ),
        migrations.DeleteModel(
            name='Factura',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
        migrations.DeleteModel(
            name='Producto_Cliente',
        ),
    ]
